name: Build And Deliver Tokens

on:
  push:
    paths:
      - "input/**"

jobs:
  # Add a job for every additional consumer/application
  generate_tokens:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install Node Dependencies
        run: npm install
      - name: Build Style Dictionary
        run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build design tokens