name: Publish Packages

on:
  push:
    paths:
      - "packages/**"

jobs:
  publish_packages:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install Dependencies
        run: yarn install
      - name: Install npm-login-cli
        run: lerna exec -- yarn add -D npm-cli-login
      - name: Log Into NPM
        run: lerna exec -- NPM_USER=${{ secrets.NPM_USER }} NPM_PASS=${{ secrets.NPM_PASS }} NPM_EMAIL=${{ secrets.NPM_EMAIL }} npm-cli-login
      - name: Publish Packages 
        run: yarn run publish