name: Publish Packages

on:
  push:
    paths:
      - "packages/**"

jobs:
  publish_packages:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install Dependencies
        run: yarn global add lerna
      - name: Publish With Lerna
        run: lerna publish from-git --yes